### ISSUE TITLE
請問一下 使用VisualBundle開啟檔案出現錯誤

### ISSUE THREAD

**Issue by smart8546** [aianlinb/LibBundle#12]
我下載code 下來後使用C#去build release 的EXE 載入_.index.bin 出現以下錯誤訊息
System.BadImageFormatException: 試圖載入格式錯誤的程式。 (Exception from HRESULT: 0x8007000B)
   at LibBundle.BundleContainer.OodleLZ_Decompress(Byte[] buffer, Int32 bufferSize, Byte[] result, Int64 outputBufferSize, Int32 a, Int32 b, Int32 c, IntPtr d, Int64 e, IntPtr f, IntPtr g, IntPtr h, Int64 i, Int32 ThreadModule)
   at LibBundle.BundleContainer.Read(BinaryReader br) in E:\POE\3.12\LibBundle-master\LibBundle\BundleContainer.cs:line 130
   at LibBundle.IndexContainer..ctor(String path) in E:\POE\3.12\LibBundle-master\LibBundle\IndexContainer.cs:line 19
   at VisualBundle.MainWindow.OnLoaded(Object sender, RoutedEventArgs e) in E:\POE\3.12\LibBundle-master\VisualBundle\MainWindow.xaml.cs:line 85
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by aianlinb** [comment]
The build target must be x64

**Comment by aianlinb** [comment]
@smart8546 
![image](https://user-images.githubusercontent.com/29705994/94517731-24f13880-025b-11eb-8bf6-44636dd7517d.png)
