### ISSUE TITLE
Error when opening any _index

### ISSUE THREAD

**Issue by poeAddict** [aianlinb/LibBundle#9]
`System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at LibBundle.BundleContainer.OodleLZ_Decompress(Byte[] buffer, Int32 bufferSize, Byte[] result, Int64 outputBufferSize, Int32 a, Int32 b, Int32 c, IntPtr d, Int64 e, IntPtr f, IntPtr g, IntPtr h, Int64 i, Int32 ThreadModule)
   at LibBundle.BundleContainer.Read(BinaryReader br) in C:\LibBundle-master (1)\LibBundle-master\LibBundle\BundleContainer.cs:line 131
   at LibBundle.IndexContainer..ctor(String path) in C:\LibBundle-master (1)\LibBundle-master\LibBundle\IndexContainer.cs:line 19
   at VisualBundle.MainWindow.OnLoaded(Object sender, RoutedEventArgs e) in C:\LibBundle-master (1)\LibBundle-master\VisualBundle\MainWindow.xaml.cs:line 85
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by aianlinb** [comment]
Is your operating system 32-bit?
This program only support 64-bit.

**Comment by poeAddict** [comment]
No, ofc not. Win10 x64 latest build.

**Comment by aianlinb** [comment]
I have no idea.
I've never had this situation.
